version: '3.5'

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=my_db
      - POSTGRES_USER=edu
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - ./postgres_data:/var/lib/postgresql